# Generated by Django 5.1.1 on 2024-12-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='image',
        ),
        migrations.AddField(
            model_name='donationform',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
