# Generated by Django 5.1.1 on 2024-12-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_donationform_image_donationform_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='image_url',
        ),
        migrations.AddField(
            model_name='donationform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
