# Generated by Django 5.1.4 on 2024-12-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_donationform_height_alter_donationform_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='donationform',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='NgoDonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('number_or_link', models.CharField(max_length=40)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_method', to='application.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NgoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/ngo')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='application.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NgoNeeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed', to='application.ngo')),
            ],
        ),
    ]
