# Generated by Django 5.1.1 on 2024-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_donationform_height_alter_donationform_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationform',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationform',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationform',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
