# Generated by Django 5.1.1 on 2024-12-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_donationform_height_alter_donationform_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NGOGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ngos/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='ngos/covers/')),
                ('about', models.TextField()),
                ('needs', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('exact_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('other_donation_methods', models.TextField()),
                ('categories', models.ManyToManyField(to='application.ngocategory')),
                ('gallery', models.ManyToManyField(to='application.ngogallery')),
            ],
        ),
    ]
