# Generated by Django 5.1.1 on 2024-12-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
