# Generated by Django 5.1.1 on 2024-12-16 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_ngo_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='ngo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.ngo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationform',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationform',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
