# Generated by Django 5.1.1 on 2024-12-16 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_donationform_ngo_alter_donationform_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='gallery',
        ),
        migrations.AddField(
            model_name='ngogallery',
            name='ngo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='application.ngo'),
            preserve_default=False,
        ),
    ]
